### ISSUE TITLE
JAZ file for loop function is wrongly defined 

### ISSUE THREAD

**Issue by vishwajeety12** [iden3/circomlib#65]
Inside the SHA-256 > main.circom 
There is a line - [include "sha256_2.jaz";](https://hexang.com/yh/circom/-/blob/281b52339c2717a1b3a519b12661912220f35d89/circuits/sha256/sha256_2.jaz)

And this is the code of sha256_2.jaz -

`
component num2bits[2] = Num2Bits(216);
    component bits2num = Bits2Num(216);

    num2bits[0].inp <== a;
    num2bits[1].inp <== b;

    component sha256compression = Sha256compression() ;

    var i;

    for (i=0; i<216; i++) {
        sha256compression.inp[i] <== num2bits[0].out[i];
        sha256compression.inp[i+216] <== num2bits[1].out[i];
    }

    [for (i=432; i<247; i++) {](https://hexang.com/yh/circom/-/blob/281b52339c2717a1b3a519b12661912220f35d89/circuits/sha256/sha256_2.jaz)
        sha256compression.inp[i] <== 0;
    }
`

What is the use of second loop? Because by definition it does nothing.

**Comment by poma** [comment]
Probably should be `i<447` and similar changes on the next line.

You issue seems to be for some ancient file that was deleted a long time ago.
