### ISSUE TITLE
Question about Num2Bits

### ISSUE THREAD

**Issue by saideng** [iden3/circomlib#82]
Originally:
```
template Num2Bits(n) {
    signal input in;
    signal output out[n];
    var lc1=0;

    var e2=1;
    for (var i = 0; i<n; i++) {
        out[i] <-- (in >> i) & 1;
        out[i] * (out[i] -1 ) === 0;
        lc1 += out[i] * e2;
        e2 = e2+e2;
    }

    lc1 === in;
}
```
But I think the last check is not secure, since lc1 is not a singal.
A possible modification would be:
```
template Num2Bits(n) {
    signal input in;
    signal output out[n];
    signal lc1[n+1];
    lc1[0] <== 0;
    var e2 = 1;

    for (var i = 0; i<n; i++) {
        out[i] <-- (in >> i) & 1;
        out[i] * (out[i] -1 ) === 0;
        lc1[i+1] <== out[i] * e2 + lc1[i];
        e2 = e2 + e2;
    }

    lc1[n] === in;
}
```

**Comment by saideng** [comment]
Also, should e2 be a signal array?

**Comment by MisakaCenter** [comment]
It's inefficient and since Num2Bit is widely-used it's painful to add this change. Also, can you elaborate on why it is not secure? It seems good to me. @saideng

**Comment by saideng** [comment]
> It's inefficient and since Num2Bit is widely-used it's painful to add this change. Also, can you elaborate on why it is not secure? It seems good to me. @saideng

Thanks for the reply.
I already realized that they are the same.
