### ISSUE TITLE
Tests fail on fresh setup

### ISSUE THREAD

**Issue by jeffreyscholz** [iden3/circomlib#83]
Steps to reproduce

```bash
git clone https://github.com/iden3/circomlib.git
cd circomlib
npm install
npm test
```

On the latest commit `cff5ab6288b55ef23602221694a6a38a0239dcc0`

<img width="973" alt="Screen Shot 2022-11-07 at 3 10 00 PM" src="https://user-images.githubusercontent.com/6095539/200258800-b1c3efa5-57b7-48cf-bcad-611d91f72c9e.png">

**Comment by supragya** [comment]
Facing a similar issue. Any resolution for the above?

**Comment by simon-perriard** [comment]
I bumped the version of ``circom_tester`` from ``0.0.13`` to ``0.0.19`` and it worked :) tell me if it solved your problem

**Comment by jeffreyscholz** [comment]
Verifying the change fixes the problem! Please feel free to close this issue when the PR is merged.

**Comment by simon-perriard** [comment]
@jeffreyscholz can you close this issue please :) ?
