### ISSUE TITLE
Question about BabyPbk babyjub.circom 

### ISSUE THREAD

**Issue by saiakilesh** [iden3/circomlib#88]
https://github.com/iden3/circomlib/blob/master/circuits/babyjub.circom#L96-L97

Why in this circuit is there a check that the private key is within 253 bits? I thought valid private keys are within 254 bit prime field corresponding to BN254?

**Comment by simon-perriard** [comment]
If you follow the standard for key generation https://www.rfc-editor.org/rfc/rfc8032#section-5.1.5, ``s`` is 256 bits long after step 2, then the [public key extraction implemented in ``circomlibjs``](https://github.com/iden3/circomlibjs/blob/4f094c5be05c1f0210924a3ab204d8fd8da69f49/src/eddsa.js#L40) shifts everything to the right by 3 bits, hence 253 bits for the private key. Did this help?

**Comment by saiakilesh** [comment]
> If you follow the standard for key generation for EdDSA https://www.rfc-editor.org/rfc/rfc8032#section-5.1.5, `s` is 256 bits long after step 2, then the [public key extraction implemented in `circomlibjs`](https://github.com/iden3/circomlibjs/blob/4f094c5be05c1f0210924a3ab204d8fd8da69f49/src/eddsa.js#L40) shifts everything to the right by 3 bits, hence 253 bits for the private key. Did this help?

Yes thank you.

**Comment by simon-perriard** [comment]
@saiakilesh can you close the issue if it is solved please?
